### ISSUE TITLE
Question about x-axis bounds

### ISSUE THREAD

**Issue by Eneswar** [DylanHojnoski/obsidian-graphs#18]
Lets say I have this graph:

```graph
bounds: [-2,7,7,-2]
elements: [
	{type: "point", def: [4,5], att: {withLabel: false}},
	{type: "arrow", def: [[0,0],"e0"], att: {strokeColor: "red", fillOpacity: 1, name: "(a, b)", withLabel: true}},
	{type: "point", def: [6,0], att: {withLabel: false}},
	{type: "arrow", def: [[0,0],[6,0]], att: {strokeColor: "blue", fillOpacity: 1, name: "x", withLabel: true}},
	{type: "point", def: [0,5], att: {withLabel: false}},
	{type: "arrow", def: [[0,0],[0,5]], att: {strokeColor: "blue", fillOpacity: 1, name: "b", withLabel: true}},
	{type: "point", def: [4,0], att: {withLabel: false}},
	{type: "arrow", def: [[0,0],[4,0]], att: {strokeColor: "yellow", fillOpacity: 1, name: "a", withLabel: true}},
	{type: "segment", def: ["e0", ["f:e0.X()", 0]], att: {dash: 2}, att: {dash: 3, name: "x", withLabel: false}},
	{type: "segment", def: ["e0", [0,"f:e0.Y()"]], att: {dash: 3, name: "y", withLabel: false}},
]
```

![image](https://github.com/DylanHojnoski/obsidian-graphs/assets/22943781/2033291b-32dc-4dc0-8ece-9fb4b1d51ea1)

As you can clearly see the x-axis is stretched out. Is that always ment to happen? It seems no matter how I change the bounds the x-axis always seems to be this stretched out or am I missing something?

**Comment by DylanHojnoski** [comment]
You can set the setting `keepAspectRatio: true` so that the x-axis is not stretched.

I also just released settings for the height and width of the graph so you can control the size in pixels it is within your notes. So if you set it up to be a square like `height: 300` `width: 300` the axis won't be stretched.

```
bounds: [-2,7,7,-2]
keepAspectRatio: true
elements: [
	{type: "point", def: [4,5], att: {withLabel: false}},
	{type: "arrow", def: [[0,0],"e0"], att: {strokeColor: "red", fillOpacity: 1, name: "(a, b)", withLabel: true}},
	{type: "point", def: [6,0], att: {withLabel: false}},
	{type: "arrow", def: [[0,0],[6,0]], att: {strokeColor: "blue", fillOpacity: 1, name: "x", withLabel: true}},
	{type: "point", def: [0,5], att: {withLabel: false}},
	{type: "arrow", def: [[0,0],[0,5]], att: {strokeColor: "blue", fillOpacity: 1, name: "b", withLabel: true}},
	{type: "point", def: [4,0], att: {withLabel: false}},
	{type: "arrow", def: [[0,0],[4,0]], att: {strokeColor: "yellow", fillOpacity: 1, name: "a", withLabel: true}},
	{type: "segment", def: ["e0", ["f:e0.X()", 0]], att: {dash: 2}, att: {dash: 3, name: "x", withLabel: false}},
	{type: "segment", def: ["e0", [0,"f:e0.Y()"]], att: {dash: 3, name: "y", withLabel: false}},
]
```

**Comment by Eneswar** [comment]
That was a quick update, thank you very much, apprecaite it! Looks good now.

**Comment by Eneswar** [comment]
By the way something that keeps happening to me randomly is that sometimes when I open a note with a graph it doesnt show until I select the area where the graph is. Im not sure why it happens.

![image](https://github.com/DylanHojnoski/obsidian-graphs/assets/22943781/c338b1ab-2d6a-44e5-a6b7-cdafcb4c69cd)

![image](https://github.com/DylanHojnoski/obsidian-graphs/assets/22943781/e89232cc-b840-4425-84e5-c10121b1eb4f)

**Comment by DylanHojnoski** [comment]
Are you using live preview or source mode?

**Comment by Eneswar** [comment]
This is all live preview.

**Comment by DylanHojnoski** [comment]
I can't seem to replicate this bug. How often is it happening?

**Comment by Eneswar** [comment]
Well it hasnt happened again since I posted about it so we might be good :P

**Comment by Eneswar** [comment]
I figured out why, or how, it happens, and it happens every time.

When I am in a note with a graph, and I go to another one, and then when I go back (not by clicking on the note, but by going back one step, example with my side mouse button) the graphs will not display.

Its not the biggest deal but I wanted to let you know.
