### ISSUE TITLE
Sliders and functions didn't work as explained

### ISSUE THREAD

**Issue by mineraloge** [DylanHojnoski/obsidian-graphs#2]
Hello,
if I try your Sin Riemannsum example, it didn't work.
I get this error message:

TypeError: Cannot read properties of undefined (reading '1')

Thanks for your help,
Robert

**Comment by DylanHojnoski** [comment]
Are you on the latest version? I ran into this yesterday and pushed a fix. If you are on the latest version let me know and I'll look into it.

**Comment by mineraloge** [comment]
Thank you, that fixed it.
Nice extension.

Robert Koch, Dipl.-Min. 

Hohensteinweg 28
30419 Hannover

Mail: ***@***.***
Mobil: 0157 50124553
