### ISSUE TITLE
Feature request: A black/white that changes based on light/ dark theme

### ISSUE THREAD

**Issue by Bloe1901** [DylanHojnoski/obsidian-graphs#36]
Hi, this is a feature request. Can you add a black/white color that changes depending on the color theme you are in? The --mono-rgb-0 variable of obsidian lets you do that, and it would be very useful. 

I have checked the wiki very thoroughly before this. So sorry if this feature already exists and I accidentally created a redundant issue. If that is the case, please tell me how to change elements into that color.

Thank you!

**Comment by DylanHojnoski** [comment]
Do you mean that you want the color to change based on the light or dark theme? Such that with "black" when on light theme it would appear black but on dark theme it would appear white.

**Comment by Bloe1901** [comment]
Yes! That is what I meant

**Comment by DylanHojnoski** [comment]
So if you can do `"var(--color-base-100)"` to get that result. 

I don't know if overriding "black" and "white" to this would be a good idea because some one might want actual black and white but having a different word, I think "contrast" is good, is definitely something I will add.

**Comment by Bloe1901** [comment]
Thank you so much !

**Comment by DylanHojnoski** [comment]
I just published a new release with this change so you can now use the "contrast" keyword for for alternating black and white colors.

**Comment by Bloe1901** [comment]
This is very nice, thanks!
