### ISSUE TITLE
Plots not visible

### ISSUE THREAD

**Issue by amatya-aditya** [DylanHojnoski/obsidian-graphs#53]
After the latest update, the line renders correctly, but the functions are not displaying. See the images below for reference:

![image](https://github.com/user-attachments/assets/16a0e1ab-7f3e-49b8-bc39-001bd4b19c15)
![image](https://github.com/user-attachments/assets/76cfb4ae-1f35-45b5-ad81-38b54bc03d41)

Additionally, the plots don’t appear in reading mode, only in live mode. The first time this issue occurred, reinstalling the plugin fixed it for reading mode, but now it won’t render in reading mode anymore.

**Comment by DylanHojnoski** [comment]
Thanks for bringing this to my attention. I just pushed an update to fix it not rendering in read mode let me know if it is still broken.

 I could not replicate the function not working but maybe it was related to the same issue so please let me know if that is still not working.
