### ISSUE TITLE
[Feature Request] Hide 3d Axes

### ISSUE THREAD

**Issue by Bloe1901** [DylanHojnoski/obsidian-graphs#55]
Hi, I would really like to hide the axes of the bounds3d. I'm doing pure 3d geometry, so the axes really distract me. 
I don't know if this feature has already existed or not, I have checked the wiki and the JSX reference site and yet to find a way to implement this. So, if this feature does exist, please tell me. Otherwise, please implement this feature as it will open up so many more possibilities for 3d geometry! 
Thank you for this plugin and your efforts!

**Comment by Bloe1901** [comment]
I don't know if I should create a new issue, but I want to ask a question also. Is the 'strokeColor' attribute not changing the strokes' color of the polygon3d intended? I currently have to overlay lines over the strokes of the polygon to make it the color i want.

**Comment by DylanHojnoski** [comment]
To hide the axes you can use the `axesPosition` attribute.

```yaml
att3d: 
  axesPosition: none
```

For the polygon3d and polygon elements to change the colors of the lines you have to use the `borders` subelment  and to change the points you use the `vertices` subelement. I actually didn't know about this so thanks for asking.

```js
{type: polygon3d,
def: [[3,3,0],[1,1,1],[-1,-1,-1]],
att: {borders: {strokeColor: red}, vertices: {fillColor: red, strokeColor: red}}}
```

If you have more questions feel free to ask. I plan on overhauling the wiki soon so if there is anything not on the wiki but you think should be let me know.

**Comment by Bloe1901** [comment]
Thank you for responding! 
Can you provide an example for the axesPositition attribute in full context of a code? It doesn't seem to be working for me and I'm afraid that could be because of my own incompetence. 
About the wiki, obviously I would really appreciate if you can add more documentations for the 3d elements!

**Comment by DylanHojnoski** [comment]
This produces a graph without the 3d axes.

````
```graph
bounds: [10,20,20,10]
bounds3d: [[-8, 8], [-8,8], [-8,8]]
axis: false
att3d: {
	axesPosition: none
}
```
````

![no-3d-axes](https://github.com/user-attachments/assets/967dc4c3-3cc6-4cee-b764-18407667f87d)

**Comment by DylanHojnoski** [comment]
No problem you can remove the planes using the `xPlaneRear: {visible :false}` and do that for the x, y, and z planes.

````
```graph
bounds: [10,20,20,10]
bounds3d: [[-8, 8], [-8,8], [-8,8]]
axis: false
att3d: {
	axesPosition: none,
	xPlaneRear: {visible: false},
	yPlaneRear: {visible: false},
	zPlaneRear: {visible: false}
}
elements: [
	{type: parametricsurface3d, def: ["f:(2+cos(x))*cos(y)" , "f:(2+cos(x))*sin(y)", "f:sin(x)", [-5, "f:2*PI"], [-5, "f:PI"]]},
]
```
````
![no-axis-or-planes](https://github.com/user-attachments/assets/59342f77-8104-473f-84ec-f9da1ac8688e)

**Comment by DylanHojnoski** [comment]
Yeah you can switch it to perspective view by setting the projection to central.
```
att3d: {
	projection: central
}
```

**Comment by Bloe1901** [comment]
This is very nice! Thank you so much!

**Comment by Bloe1901** [comment]
Since you haven't closed the issue, do you mind if I ask some other questions ? Sorry to bother you if this is too much. 
Can you make it so that lines that are behind transparent elements are more obfuscated ? Or lines that can't be seen through are dashed lines?

**Comment by DylanHojnoski** [comment]
No problem with asking questions. There is not a simple built in option for this. I think it can be done through some calculations to figure out what objects are in front of other objects based on the camera view. The 3D features of JSXGraph are still being built out so this functionality may eventually be built into the library.

**Comment by Bloe1901** [comment]
Thank you so much!
